# Change these first
owner: MitichPavel # Your GitHub organization or username, where this repository lives
repo: eb24-status # The name of this repository

sites:
  - name: EB24 Homepage
    url: https://eloboost24.eu.com
  - name: EB24 Marketplace LOL Accounts
    url: https://eloboost24.eu/marketplace/accounts/league-of-legends
  - name: EB24 Marketplace LOL Items
    url: https://eloboost24.eu/marketplace/items/league-of-legends
  - name: EB24 LOL Coaching
    url: https://eloboost24.eu/coaching/league-of-legends
  - name: EB24 LOL GGirls
    url: https://eloboost24.eu/ggirls/league-of-legends
  - name: EB24 LOL Swift Pass Boosting
    url: https://eloboost24.eu/boosting/swift-pass
  - name: EB24 LOL Pro Games
    url: https://eloboost24.eu/pro-games/league-of-legends
  - name: EB24 Blog
    url: https://eloboost24.eu/blog

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://mitichpavel.github.io
  baseUrl: /eb24-status
  logoUrl: http://eloboost24.eu/favicon/apple-icon-180x180.png
  name: Eloboost24.eu status
  introTitle: "**Eloboost24** status page created with upptime. Upptime is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
