# Change these first
owner: MitichPavel # Your GitHub organization or username, where this repository lives
repo: eb24-status # The name of this repository

sites:
  - name: Homepage
    url: https://eloboost24.eu
  - name: Accounts LOL Accounts
    url: https://eloboost24.eu/marketplace/accounts/league-of-legends
  - name: Items LOL Items
    url: https://eloboost24.eu/marketplace/items/league-of-legends
  - name: Coaching LOL
    url: https://eloboost24.eu/coaching/league-of-legends
  - name: GGirls LOL
    url: https://eloboost24.eu/ggirls/league-of-legends
  - name: Boosting LOL Swift Pass
    url: https://eloboost24.eu/boosting/swift-pass
  - name: Pro Games LOL
    url: https://eloboost24.eu/pro-games/league-of-legends
  - name: Blog
    url: https://eloboost24.eu/blog
  - name: "Purchase: Boosting Flow"
    url: https://raw.githubusercontent.com/MitichPavel/eb24-status/master/status-data/boosting.html
    __dangerous__body_down: "purchase flow is down"

  - name: "Purchase: Coaching Flow"
    url: https://raw.githubusercontent.com/MitichPavel/eb24-status/master/status-data/coaching.html
    __dangerous__body_down: "purchase flow is down"

  - name: "Purchase: Accounts Flow"
    url: https://raw.githubusercontent.com/MitichPavel/eb24-status/master/status-data/accounts.html
    __dangerous__body_down: "purchase flow is down"

  - name: "Purchase: Items Flow"
    url: https://raw.githubusercontent.com/MitichPavel/eb24-status/master/status-data/items.html
    __dangerous__body_down: "purchase flow is down"

  - name: "Purchase: GGirls Flow"
    url: https://raw.githubusercontent.com/MitichPavel/eb24-status/master/status-data/ggirls.html
    __dangerous__body_down: "purchase flow is down"

  - name: "Purchase: Pro Games Flow"
    url: https://raw.githubusercontent.com/MitichPavel/eb24-status/master/status-data/progames.html
    __dangerous__body_down: "purchase flow is down"

notifications:
  - type: telegram
    bot-token: $TELEGRAM_BOT_TOKEN
#   - type: slack
#     webhook-url: "$SLACK_CRITICAL_WEBHOOK"

message-template: |
  🚨 *Alert:* $SITE_NAME is $STATUS

  *Health Check URL:* $SITE_URL
  *HTML Report & Screenshot:* $SITE_URL/../$SITE_NAME.html
  *Time:* $TIMESTAMP

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://mitichpavel.github.io
  baseUrl: /eb24-status
  logoUrl: http://eloboost24.eu/favicon/apple-icon-180x180.png
  name: Eloboost24.eu status
  introTitle: "**Eloboost24** status page created with Upptime."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
